name: "Strict Merge Policy: val or revert -> prod"

on:
  pull_request:
    branches:
      - prod  # 目標是prod時觸發

# 只有 val 跟 revert可以跟prod pull request
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          # github.head_ref 是 PR 的来源分支 
          echo "Source branch is: ${{ github.head_ref }}"
          
          case "${{ github.head_ref }}" in
            val | revert-[0-9]*)
              echo '分支檢查通過!'
              ;; 
            *)
              echo "本專案限制只能從 'val' 或 'revert' 分支合併到 'prod'。"
              exit 1
              ;;
          esac